sudo: required
services:
  - docker

before_install:
  - docker build -t gauravjain449/simple-app -f Dockerfile.dev .

script:
  - docker run -e CI=true gauravjain449/simple-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: ""
  bucket_path: "docker-react"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  