pipeline:
  agent:
    mage: "node:alpine"
  environment:
    CI: "true"
  options:
    timeout:
      time: 1
      unit: "HOURS"
  stages:
    stage: 
      Install_Dependencies:
        steps: 
          - npm install
    stage:
      Unit_Tests:
        steps: 
          - npm run test
