pipeline:
  agent:
    image: "node:alpine"
  environment:
    CI: "true"
  options:
    timeout:
      time: 1
      unit: "HOURS"
  steps:
    analysis:
      - npm install
      - bundle exec rubycritic --path ./analysis --minimum-score 80 --no-browser
    setup_db:
      - bundle exec rails db:create
      - bundle exec rails db:schema:load
    test:
      - bundle exec rspec
    security:
      - bundle exec brakeman --exit-on-error
    audit:
      - bundle audit check --update
