pipeline:
  agent:
    mage: "node:alpine"
  environment:
    CI: "true"
  options:
    timeout:
      time: 1
      unit: "HOURS"
  steps:
    analysis:
      - npm install      
    setup_db:
      - npm run test  
    test:
      - bundle exec rspec
    security:
      - bundle exec brakeman --exit-on-error
    audit:
      - bundle audit check --update
